services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - minio
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/Users/teoxxid/minio-data:/data
    command: server /data --console-address ":9001"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
