services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - minio
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - default

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - default

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - default

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/Users/teoxxid/minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_DISABLE_GRAFANA_AUTO_UPDATE=true  # ← ДОБАВЬТЕ ЭТУ СТРОКУ
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - default

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: marketplace_network
    